#!/bin/bash
set -euo pipefail

/usr/local/bin/mise trust /workspaces/ubuntu/mise.toml
/usr/local/bin/mise install

if [ ! -d "$HOME/.local/share/chezmoi/.git" ]; then
    sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply git@github.com:kubelaba/dotfiles.git
else
    chezmoi apply
fi

exit 0
